package app.dewey.index

import com.google.common.truth.Truth.assertThat
import kotlinx.serialization.Serializable
import kotlinx.serialization.json.Json
import org.junit.Assume.assumeTrue
import org.junit.BeforeClass
import org.junit.Test
import java.io.File

/**
 * Checks the tokenizer against the reference implementation's output.
 *
 * This is the test that matters most in the index pipeline. A wrong tokenizer
 * does not throw — it returns plausible ids that produce plausible vectors that
 * quietly rank the wrong document first. Only comparison against a known-good
 * implementation catches that, so the fixtures are generated by HuggingFace
 * `tokenizers` in tools/model/prepare_assets.py and committed alongside.
 */
class SentencePieceTokenizerTest {

    @Serializable
    data class Fixture(val text: String, val ids: List<Int>, val tokens: List<String>)

    companion object {
        private lateinit var tokenizer: SentencePieceTokenizer
        private lateinit var fixtures: List<Fixture>

        @BeforeClass
        @JvmStatic
        fun load() {
            val vocab = File("src/main/assets/models/tokenizer.bin")

            // The vocabulary is derived from a third-party model and is not
            // committed, so a fresh clone does not have it. Skipping rather than
            // failing keeps `gradlew build` green on a clean checkout — but
            // loudly, because a conformance test that quietly stops running is
            // worse than one that fails.
            if (!vocab.exists()) {
                System.err.println(
                    "SKIPPING tokenizer conformance: ${vocab.path} is absent.\n" +
                        "  Run tools/eval/fetch_model.sh, then\n" +
                        "  python tools/model/prepare_assets.py --model-dir tools/eval/model"
                )
            }
            assumeTrue("encoder assets not prepared", vocab.exists())

            tokenizer = vocab.inputStream().use(SentencePieceTokenizer::load)

            val json = File("src/test/resources/tokenizer_fixtures.json").readText()
            fixtures = Json { ignoreUnknownKeys = true }.decodeFromString(json)
        }
    }

    @Test
    fun `loads the full vocabulary`() {
        assertThat(tokenizer.vocabularySize).isEqualTo(250_002)
    }

    @Test
    fun `matches the reference on every fixture`() {
        val mismatches = fixtures.mapNotNull { fixture ->
            val actual = tokenizer.encode(fixture.text).toList()
            if (actual == fixture.ids) null else fixture to actual
        }

        // Reported together rather than failing on the first: when a
        // normalisation rule is wrong, seeing which inputs it affects is what
        // identifies the rule.
        val report = mismatches.joinToString("\n") { (fixture, actual) ->
            "  ${fixture.text.take(45).replace("\n", "\\n")}\n" +
                "    want ${fixture.ids.take(14)}\n" +
                "    got  ${actual.take(14)}"
        }
        assertThat(report).isEmpty()
    }

    @Test
    fun `empty text is just the boundary tokens`() {
        assertThat(tokenizer.encode("").toList()).containsExactly(0, 2).inOrder()
    }

    @Test
    fun `every result is bounded by the boundary tokens`() {
        for (fixture in fixtures) {
            val ids = tokenizer.encode(fixture.text)
            assertThat(ids.first()).isEqualTo(0)
            assertThat(ids.last()).isEqualTo(2)
        }
    }

    @Test
    fun `respects the token budget`() {
        val long = "Facture Lydec electricite et eau ".repeat(400)

        val ids = tokenizer.encode(long, maxTokens = 64)

        assertThat(ids).hasLength(64)
        assertThat(ids.first()).isEqualTo(0)
        assertThat(ids.last()).isEqualTo(2)
    }

    @Test
    fun `never emits an id outside the vocabulary`() {
        // An out-of-range id is an array index crash inside ONNX Runtime, which
        // surfaces as an opaque native error rather than anything diagnosable.
        val hostile = fixtures.map(Fixture::text) + listOf(
            "\u0000\u0001\u0002", "\uD800", "\uDC00", "\uFFFF", "\u200B\u200C\u200D",
        )
        for (text in hostile) {
            for (id in tokenizer.encode(text)) {
                assertThat(id).isAtLeast(0)
                assertThat(id).isLessThan(tokenizer.vocabularySize)
            }
        }
    }

    @Test
    fun `survives lone surrogates and control characters`() {
        val nasty = listOf(
            "\uD83D", "\uDE00", "a\uD83Db", "\u0000text\u0000",
            "\uFEFFbom", "text\u0007bell", "\u00A0nbsp\u00A0",
        )
        for (text in nasty) {
            val ids = tokenizer.encode(text)
            assertThat(ids.size).isAtLeast(2)
        }
    }

    @Test
    fun `handles very long single words`() {
        val ids = tokenizer.encode("a".repeat(5_000))

        assertThat(ids.size).isAtMost(512)
        assertThat(ids.last()).isEqualTo(2)
    }

    @Test
    fun `rejects a token budget with no room for content`() {
        assertThat(runCatching { tokenizer.encode("test", maxTokens = 1) }.isFailure).isTrue()
    }
}
